defaults:
  - xception
data:
  train_csv: ./data/splits_200video_15frames/train.csv
  val_csv: ./data/splits_200video_15frames/val.csv
  test_csv: ./data/splits_200video_15frames/test.csv
logging:
  output_dir: ./outputs/200video
training:
  batch_size: 8
  pin_memory: false
